[functions]
[functions.crear-usuario]
verify_jwt = false

[functions.editar-usuario]
verify_jwt = false

[functions.generar-numero-documento]
verify_jwt = false

[functions.crear-documento]
verify_jwt = false
